name: heraninda_task
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  awesome_flutter_extensions: ^1.3.0
  intl: any
  icons_plus: ^5.0.0
  google_nav_bar: ^5.0.7
  pin_input_text_field: ^4.5.2
  auto_validate: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Instrument Sans
      fonts:
        - asset: assets/fonts/InstrumentSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/InstrumentSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/InstrumentSans-Bold.ttf
          weight: 700
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

flutter-assets:
  auto-generate: false
  assets-path: assets/
  output-path: lib/core/constants/
  ignore-ext: false
  filename: assets.dart
